///
/// @brief      Tag definitions for video input
///

#ifndef IVDRVIDEOINPUTTAGS_H
#define IVDRVIDEOINPUTTAGS_H

#include "VDR/Interface/Unit/Video/Display/IVDRVideoTypes.h"

// Input video input TAG ID.
// TAG IDs created by the VDR ID value manager
static const VDRTID VDRTID_VIDEO_INPUT = 0x0003b000;


MKTAG(VIDEO_INPUT_SIGNALLOCKED,					VDRTID_VIDEO_INPUT,	0x001, bool)
MKTAG(VIDEO_INPUT_COLORSTANDARD,					VDRTID_VIDEO_INPUT,	0x002, ColorStandard)
MKTAG(VIDEO_CURRENT_COLORSTANDARD,				VDRTID_VIDEO_INPUT,	0x003, ColorStandard)
MKTAG(VIDEO_INPUT_FIELDFREQENCY,					VDRTID_VIDEO_INPUT,	0x004, uint32)
MKTAG(VIDEO_INPUT_INTERLACED,						VDRTID_VIDEO_INPUT,	0x005, bool)
MKTAG(VIDEO_INPUT_MACROVISION,					VDRTID_VIDEO_INPUT,	0x006, bool)
MKTAG(VIDEO_INPUT_ASPECTRATIO,               VDRTID_VIDEO_INPUT,	0x007, VideoPresentationMode)
MKTAG(VIDEO_CURRENT_VIDEOTYPE,    				VDRTID_VIDEO_INPUT,	0x008, VideoSource)


#endif // IVDRVIDEOINPUTTAGS_H
